# Generated by Django 3.0.4 on 2020-03-24 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fake', '0003_auto_20200324_0721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='date',
        ),
    ]
